name: stuverse_ai
description: Stuverse AI Chat bot
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.5.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_bubble: ^2.0.2
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  go_router: ^13.0.1
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
